import { generateId } from "./utils"
import type { FormData } from "@/types/form"

export const PRESET_TEMPLATES: Record<string, FormData> = {
  feedback: {
    id: generateId(),
    title: "Premium Feedback Form",
    description: "Tell us what you think about our premium service.",
    pages: [
      {
        id: generateId(),
        title: "Introduction",
        type: "welcome",
        layout: {
          canvasBackground: "#0f172a",
          canvasGradient: { enabled: true, type: "linear", colors: ["#0f172a", "#1e1b4b"], angle: 135 },
          maxWidth: "md",
          backgroundColor: "rgba(255, 255, 255, 0.05)",
          backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f8fafc"], angle: 180 },
          borderColor: "rgba(255, 255, 255, 0.1)",
          borderWidth: 1,
          borderRadius: 32,
          shadow: { enabled: true, x: 0, y: 30, blur: 60, spread: -12, color: "rgba(0,0,0,0.5)" },
          padding: { top: 60, right: 40, bottom: 60, left: 40 },
          textColor: "#ffffff",
          buttonColor: "#6366f1",
          buttonTextColor: "#ffffff",
          alignment: "center",
        },
        sections: [
          {
            id: generateId(),
            type: "container",
            title: "Welcome Node",
            layout: {
              width: "full",
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              backgroundColor: "transparent",
              backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f1f5f9"], angle: 180 },
              glassmorphism: { enabled: true, blur: 20, opacity: 0.1 },
              borderColor: "transparent",
              borderWidth: 0,
              borderRadius: 24,
              shadow: { enabled: false, x: 0, y: 0, blur: 0, spread: 0, color: "transparent" },
              alignment: "center",
              direction: "column",
              gap: 24,
            },
            elements: [
              { id: generateId(), type: "heading", label: "We value your opinion", required: false },
              { id: generateId(), type: "paragraph", label: "Help us improve by sharing your thoughts on the new experience.", required: false },
            ],
            children: [],
          },
        ],
      },
      {
        id: generateId(),
        title: "Feedback Details",
        type: "form",
        layout: {
          canvasBackground: "#ffffff",
          canvasGradient: { enabled: true, type: "linear", colors: ["#6366f1", "#a855f7"], angle: 45 },
          maxWidth: "md",
          backgroundColor: "#ffffff",
          backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f8fafc"], angle: 180 },
          borderColor: "#e2e8f0",
          borderWidth: 1,
          borderRadius: 40,
          shadow: { enabled: true, x: 0, y: 40, blur: 80, spread: -20, color: "rgba(0,0,0,0.15)" },
          padding: { top: 48, right: 48, bottom: 48, left: 48 },
          textColor: "#1e293b",
          buttonColor: "#7c3aed",
          buttonTextColor: "#ffffff",
          alignment: "left",
        },
        sections: [
          {
            id: generateId(),
            type: "input-zone",
            title: "Rating & Comments",
            layout: {
              width: "full",
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              backgroundColor: "transparent",
              backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f8fafc"], angle: 180 },
              glassmorphism: { enabled: false, blur: 10, opacity: 0.8 },
              borderColor: "transparent",
              borderWidth: 0,
              borderRadius: 0,
              shadow: { enabled: false, x: 0, y: 0, blur: 0, spread: 0, color: "transparent" },
              alignment: "left",
              direction: "column",
              gap: 32,
            },
            elements: [
              { id: generateId(), type: "heading", label: "Your Experience", required: false },
              { id: generateId(), type: "radio", label: "How would you rate our service?", options: ["Amazing", "Good", "Average", "Bad"], required: true },
              { id: generateId(), type: "textarea", label: "Any additional comments?", placeholder: "Tell us more...", required: false },
            ],
            children: [],
          },
        ],
      },
    ],
    settings: {
      theme: "modern",
      headerStyle: "vibrant",
      showLogo: true,
      backgroundColor: "#ffffff",
      textColor: "#000000",
    },
  },
  contact: {
    id: generateId(),
    title: "Minimalist Contact",
    description: "A clean and simple contact form for any website.",
    pages: [
      {
        id: generateId(),
        title: "Contact Us",
        type: "form",
        layout: {
          canvasBackground: "#f1f5f9",
          canvasGradient: { enabled: false, type: "linear", colors: ["#f8fafc", "#e2e8f0"], angle: 180 },
          maxWidth: "md",
          backgroundColor: "#ffffff",
          backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f8fafc"], angle: 180 },
          borderColor: "transparent",
          borderWidth: 0,
          borderRadius: 16,
          shadow: { enabled: true, x: 0, y: 4, blur: 24, spread: 0, color: "rgba(0,0,0,0.05)" },
          padding: { top: 80, right: 80, bottom: 80, left: 80 },
          textColor: "#0f172a",
          buttonColor: "#0f172a",
          buttonTextColor: "#ffffff",
          alignment: "left",
        },
        sections: [
          {
            id: generateId(),
            type: "input-zone",
            title: "Fields",
            layout: {
              width: "full",
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              backgroundColor: "transparent",
              backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f8fafc"], angle: 180 },
              glassmorphism: { enabled: false, blur: 10, opacity: 0.8 },
              borderColor: "transparent",
              borderWidth: 0,
              borderRadius: 0,
              shadow: { enabled: false, x: 0, y: 0, blur: 0, spread: 0, color: "transparent" },
              alignment: "left",
              direction: "column",
              gap: 24,
            },
            elements: [
              { id: generateId(), type: "heading", label: "Get in touch", required: false },
              { id: generateId(), type: "text", label: "Full Name", placeholder: "Jane Doe", required: true },
              { id: generateId(), type: "email", label: "Email Address", placeholder: "jane@example.com", required: true },
              { id: generateId(), type: "textarea", label: "Message", placeholder: "How can we help?", required: true },
            ],
            children: [],
          },
        ],
      },
    ],
    settings: {
      theme: "minimal",
      headerStyle: "none",
      showLogo: false,
      backgroundColor: "#ffffff",
      textColor: "#000000",
    },
  },
  registration: {
    id: generateId(),
    title: "Event RSVP",
    description: "Modern registration form for your upcoming events.",
    pages: [
      {
        id: generateId(),
        title: "Registration",
        type: "form",
        layout: {
          canvasBackground: "#ffffff",
          canvasGradient: { enabled: true, type: "radial", colors: ["#eff6ff", "#dbeafe"], angle: 0 },
          maxWidth: "md",
          backgroundColor: "#ffffff",
          backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f8fafc"], angle: 180 },
          borderColor: "#2563eb",
          borderWidth: 2,
          borderRadius: 24,
          shadow: { enabled: true, x: 0, y: 20, blur: 40, spread: -10, color: "rgba(37,99,235,0.1)" },
          padding: { top: 40, right: 40, bottom: 40, left: 40 },
          textColor: "#1e3a8a",
          buttonColor: "#2563eb",
          buttonTextColor: "#ffffff",
          alignment: "center",
        },
        sections: [
          {
            id: generateId(),
            type: "container",
            title: "Header Content",
            layout: {
              width: "full",
              padding: { top: 0, right: 0, bottom: 16, left: 0 },
              margin: { top: 0, right: 0, bottom: 24, left: 0 },
              backgroundColor: "transparent",
              backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f1f5f9"], angle: 180 },
              glassmorphism: { enabled: false, blur: 10, opacity: 0.8 },
              borderColor: "transparent",
              borderWidth: 0,
              borderRadius: 0,
              shadow: { enabled: false, x: 0, y: 0, blur: 0, spread: 0, color: "transparent" },
              alignment: "center",
              direction: "column",
              gap: 12,
            },
            elements: [
              { id: generateId(), type: "heading", label: "Tech Conference 2024", required: false },
              { id: generateId(), type: "paragraph", label: "Secure your spot at the biggest tech event of the year.", required: false },
            ],
            children: [],
          },
          {
            id: generateId(),
            type: "input-zone",
            title: "Attendee Info",
            layout: {
              width: "full",
              padding: { top: 32, right: 32, bottom: 32, left: 32 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
              backgroundColor: "#f8fafc",
              backgroundGradient: { enabled: false, type: "linear", colors: ["#ffffff", "#f1f5f9"], angle: 180 },
              glassmorphism: { enabled: false, blur: 10, opacity: 0.8 },
              borderColor: "#e2e8f0",
              borderWidth: 1,
              borderRadius: 16,
              shadow: { enabled: false, x: 0, y: 0, blur: 0, spread: 0, color: "transparent" },
              alignment: "left",
              direction: "column",
              gap: 20,
            },
            elements: [
              { id: generateId(), type: "text", label: "What is your name?", placeholder: "Your name", required: true },
              { id: generateId(), type: "email", label: "Company email", placeholder: "work@company.com", required: true },
              { id: generateId(), type: "select", label: "Experience Level", options: ["Junior", "Mid-level", "Senior", "Lead"], required: true },
            ],
            children: [],
          },
        ],
      },
    ],
    settings: {
      theme: "event",
      headerStyle: "image",
      showLogo: true,
      backgroundColor: "#ffffff",
      textColor: "#000000",
    },
  }
}
